apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
  labels: 
    name: app-1
    tier: app1-fe
spec:
  replicas: 2
  selector:
    matchLabels:
      name: app-1
      tier: app1-fe
  template:
    metadata:
      labels:
        name: app-1
        tier: app1-fe
    spec:
      containers:
      - name: app1-fe
        image: nginx
        ports:
        - containerPort: 80
