pipeline {
    agent {
        kubernetes {
            label 'k8-jenkins'
        }
    }
    stages{
        stage('testing'){
            steps {
                script {
                    sh """
                    echo "testing agent"
                    """
                }
            }
        }
    }
}