name: Build, Test, and Deploy AEM to On-Prem Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx (optional for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (or your container registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io

      # Build Docker image for AEM
      - name: Build AEM Docker image
        run: |
          docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/aem-author:latest .
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/aem-author:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up kubectl (Kubernetes CLI)
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      # Apply Kubernetes manifests
      - name: Deploy AEM to Kubernetes
        run: |
          kubectl apply -f k8s/aem-deployment.yaml
          kubectl apply -f k8s/aem-service.yaml

      # Wait for the AEM pods to be ready
      - name: Wait for AEM pods to be ready
        run: |
          kubectl rollout status deployment/aem-deployment --namespace ${{ secrets.KUBERNETES_NAMESPACE }}
